version: '3.3'

services:
  postgres-library:
    image: postgres:latest
    container_name: pg-docker-library
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGDATA
    ports:
        # Have used host port 5432 already for another project
      - 5430:5432
    volumes:
      - "./sqlQueries/db.sql:/docker-entrypoint-initdb.d/db.sql"
      # for debian system use: /var/lib/postgresql/data/:/var/lib/postgresql/data/pgdata
      # for mac OS: ./pgdata/:/var/lib/postgresql/data/pgdata and copy the CSV files under pgdata
      # which will be under the project level directory, not the root level
      - "./pgdata/:/var/lib/postgresql/data/pgdata"
  maildev:
    image: maildev/maildev
    ports:
      - "1080:80"
volumes:
  pgdata: