version: '3.3'

services:
  postgres:
    image: postgres:latest
    container_name: pg-docker
    restart: always
    environment:
      POSTGRES_DB: registration
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata/
    ports:
      - 5432:5432
    volumes:
      # for debian system use: /var/lib/postgresql/data/:/var/lib/postgresql/data/pgdata
      # for mac OS: ./pgdata/:/var/lib/postgresql/data/pgdata and copy the CSV files under pgdata
      # which will be under the project level directory, not the root level
      - "./pgdata/:/var/lib/postgresql/data/pgdata"
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf
volumes:
  pgdata: